### ISSUE TITLE
improvements and fixes of Sprint 3

### ISSUE THREAD

**Issue by lojedaa** [ISIS-3510-Mobiles/Back-End#50]
Following the viva voce for Sprint 3, we identified several key areas for improvement and fixes, including addressing usability challenges in specific features, resolving reported bugs, optimizing performance, and enhancing documentation clarity. Additionally, we received valuable feedback on potential feature refinements that require review and prioritization. These adjustments are essential to ensure the sprint deliverables meet project goals and stakeholder expectations effectively.

**Comment by davidarturolr** [comment]
We already fixed them and showed them to the professor last friday, resolving reported bugs, optimizing performance, and enhancing documentation clarity.
